### ISSUE TITLE
Build infos missing

### ISSUE THREAD

**Issue by luchaos** [ixopay/pgc-opencart#1]
The README should provide information about requirements, how to build a branded extension from source and how to provide updates for the extension.

A build script should ease the process of building branded extensions from source.

**Comment by allsecure-pay** [comment]
Hi luchaos,

Thank you for getting in touch with us. 

We have received your message and will be responding to your enquiry as soon as possible.

-------------------------------------------------------------
Date: 2019-08-30
-------------------------------------------------------------
Name: luchaos
Email: reply@reply.github.com
Group: TECNICAL SUPPORT
-------------------------------------------------------------
Closed #1 via 16708b89fae46d3917485b78caffd11d3df2708e.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/ixopay/pgc-opencart/issues/1#event-2597142590


Powered by LiveZilla Help Desk Software [https://www.livezilla.net]

Ticket History:
https://help.allsecpay.com/ticket.php?id=21154&hash=E4E8B2FAF112&salt=56b641722f1adcab4248e503e6cb34c2

[E4E8B2FAF112]
